import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import Navbar from "../components/Layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const APP_BASE_URL =
//   "https://business-backend-production-31d3.up.railway.app";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add Tailwind CDN link here */}
        <link
          href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
